# Generated by Django 4.1.6 on 2023-12-15 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GolfCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=255)),
                ("course_tee_color", models.CharField(max_length=50)),
                ("course_yardage", models.PositiveIntegerField(default=0)),
                ("course_slope", models.FloatField()),
                ("course_rating", models.FloatField()),
                ("number_of_holes", models.PositiveIntegerField()),
                ("par_value", models.PositiveIntegerField()),
            ],
            options={
                "unique_together": {("course_name", "course_tee_color")},
            },
        ),
        migrations.CreateModel(
            name="GolfHole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hole_number", models.PositiveIntegerField()),
                ("par_value", models.PositiveIntegerField()),
                ("course_hole_rating", models.FloatField()),
                ("hole_yardage", models.PositiveIntegerField()),
                (
                    "golf_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.golfcourse",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("golf_course", "hole_number", "course_hole_rating")
                },
            },
        ),
    ]
