# Generated by Django 4.1.6 on 2023-12-15 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GolfRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time_played", models.DateTimeField()),
                ("hole1_score", models.PositiveIntegerField()),
                ("hole2_score", models.PositiveIntegerField()),
                ("hole3_score", models.PositiveIntegerField()),
                ("hole4_score", models.PositiveIntegerField()),
                ("hole5_score", models.PositiveIntegerField()),
                ("hole6_score", models.PositiveIntegerField()),
                ("hole7_score", models.PositiveIntegerField()),
                ("hole8_score", models.PositiveIntegerField()),
                ("hole9_score", models.PositiveIntegerField()),
                ("hole10_score", models.PositiveIntegerField()),
                ("hole11_score", models.PositiveIntegerField()),
                ("hole12_score", models.PositiveIntegerField()),
                ("hole13_score", models.PositiveIntegerField()),
                ("hole14_score", models.PositiveIntegerField()),
                ("hole15_score", models.PositiveIntegerField()),
                ("hole16_score", models.PositiveIntegerField()),
                ("hole17_score", models.PositiveIntegerField()),
                ("hole18_score", models.PositiveIntegerField()),
                ("hole1_Putts", models.PositiveIntegerField()),
                ("hole2_Putts", models.PositiveIntegerField()),
                ("hole3_Putts", models.PositiveIntegerField()),
                ("hole4_Putts", models.PositiveIntegerField()),
                ("hole5_Putts", models.PositiveIntegerField()),
                ("hole6_Putts", models.PositiveIntegerField()),
                ("hole7_Putts", models.PositiveIntegerField()),
                ("hole8_Putts", models.PositiveIntegerField()),
                ("hole9_Putts", models.PositiveIntegerField()),
                ("hole10_Putts", models.PositiveIntegerField()),
                ("hole11_Putts", models.PositiveIntegerField()),
                ("hole12_Putts", models.PositiveIntegerField()),
                ("hole13_Putts", models.PositiveIntegerField()),
                ("hole14_Putts", models.PositiveIntegerField()),
                ("hole15_Putts", models.PositiveIntegerField()),
                ("hole16_Putts", models.PositiveIntegerField()),
                ("hole17_Putts", models.PositiveIntegerField()),
                ("hole18_Putts", models.PositiveIntegerField()),
                ("hole1_GIR", models.PositiveIntegerField()),
                ("hole2_GIR", models.PositiveIntegerField()),
                ("hole3_GIR", models.PositiveIntegerField()),
                ("hole4_GIR", models.PositiveIntegerField()),
                ("hole5_GIR", models.PositiveIntegerField()),
                ("hole6_GIR", models.PositiveIntegerField()),
                ("hole7_GIR", models.PositiveIntegerField()),
                ("hole8_GIR", models.PositiveIntegerField()),
                ("hole9_GIR", models.PositiveIntegerField()),
                ("hole10_GIR", models.PositiveIntegerField()),
                ("hole11_GIR", models.PositiveIntegerField()),
                ("hole12_GIR", models.PositiveIntegerField()),
                ("hole13_GIR", models.PositiveIntegerField()),
                ("hole14_GIR", models.PositiveIntegerField()),
                ("hole15_GIR", models.PositiveIntegerField()),
                ("hole16_GIR", models.PositiveIntegerField()),
                ("hole17_GIR", models.PositiveIntegerField()),
                ("hole18_GIR", models.PositiveIntegerField()),
                ("round_notes", models.TextField(max_length=500)),
                ("total_gir", models.CharField(max_length=18)),
                ("total_putts", models.CharField(max_length=50)),
                ("total_score", models.PositiveIntegerField()),
                ("total_holes", models.PositiveIntegerField()),
                (
                    "golf_course",
                    models.ForeignKey(
                        default="Test Golf Course Blue",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.golfcourse",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
