# Generated by Django 4.1.6 on 2023-12-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_golfround_round_differential_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="golfround",
            name="round_differential",
            field=models.FloatField(),
        ),
    ]
