# Generated by Django 4.1.6 on 2023-12-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_golfround_round_differential"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="golfround",
            name="user",
        ),
        migrations.AddField(
            model_name="golfround",
            name="username",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole10_GIR",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole10_Putts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole11_GIR",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole11_Putts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole12_GIR",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole12_Putts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole13_GIR",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole13_Putts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole14_GIR",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole14_Putts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole15_GIR",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole15_Putts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole16_GIR",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole16_Putts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole17_GIR",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole17_Putts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole18_GIR",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole18_Putts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole1_GIR",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole1_Putts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole2_GIR",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole2_Putts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole3_GIR",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole3_Putts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole4_GIR",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole4_Putts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole5_GIR",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole5_Putts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole6_GIR",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole6_Putts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole7_GIR",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole7_Putts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole8_GIR",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole8_Putts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole9_GIR",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole9_Putts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
