# Generated by Django 4.1.6 on 2023-12-28 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0004_remove_golfround_user_golfround_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="golfround",
            name="username",
        ),
        migrations.AddField(
            model_name="golfround",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
