# Generated by Django 4.1.6 on 2024-01-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_userstats_current_low_handicap_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstats",
            name="fairways_per_round",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="userstats",
            name="gir_per_round",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="userstats",
            name="low_handicap_date",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="userstats",
            name="putts_per_round",
            field=models.FloatField(blank=True),
        ),
    ]
