# Generated by Django 4.1.6 on 2024-01-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_alter_userstats_fairways_per_round_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstats",
            name="low_handicap_date",
            field=models.DateTimeField(),
        ),
    ]
