# Generated by Django 4.1.6 on 2024-02-02 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_alter_userstats_low_handicap_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "linkedin_link",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^https://www.linkedin.com/in/*"
                            )
                        ],
                    ),
                ),
                (
                    "github_link",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^https://github.com/*"
                            )
                        ],
                    ),
                ),
                (
                    "img_file",
                    models.FileField(
                        blank=True, max_length=300, null=True, upload_to=""
                    ),
                ),
                ("user_summary", models.TextField(blank=True, null=True)),
                (
                    "highest_degree",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "degree_subject",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
            ],
        ),
    ]
