# Generated by Django 4.1.6 on 2024-02-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_myprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myprofile",
            name="img_file",
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole10_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole11_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole12_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole13_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole14_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole15_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole16_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole17_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole18_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole1_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole2_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole3_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole4_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole5_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole6_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole7_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole8_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole9_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
