# Generated by Django 4.1.6 on 2024-02-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_remove_myprofile_img_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="golfround",
            name="hole10_GIR",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole11_GIR",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole12_GIR",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole13_GIR",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole14_GIR",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole15_GIR",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole16_GIR",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole17_GIR",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole18_GIR",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole1_GIR",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole2_GIR",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole3_GIR",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole4_GIR",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole5_GIR",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole6_GIR",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole7_GIR",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole8_GIR",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="golfround",
            name="hole9_GIR",
            field=models.BooleanField(null=True),
        ),
    ]
