# Generated by Django 4.1.6 on 2024-02-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_alter_golfround_hole10_gir_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="golfround",
            name="hole10_FWY",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="golfround",
            name="hole11_FWY",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="golfround",
            name="hole12_FWY",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="golfround",
            name="hole13_FWY",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="golfround",
            name="hole14_FWY",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="golfround",
            name="hole15_FWY",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="golfround",
            name="hole16_FWY",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="golfround",
            name="hole17_FWY",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="golfround",
            name="hole18_FWY",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="golfround",
            name="hole1_FWY",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="golfround",
            name="hole2_FWY",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="golfround",
            name="hole3_FWY",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="golfround",
            name="hole4_FWY",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="golfround",
            name="hole5_FWY",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="golfround",
            name="hole6_FWY",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="golfround",
            name="hole7_FWY",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="golfround",
            name="hole8_FWY",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="golfround",
            name="hole9_FWY",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="golfround",
            name="total_fwy",
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name="userstats",
            name="fairways_per_hole",
            field=models.FloatField(blank=True, default=0.8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userstats",
            name="putts_per_hole",
            field=models.FloatField(blank=True, default=3.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userstats",
            name="total_holes_played",
            field=models.PositiveIntegerField(default=18),
            preserve_default=False,
        ),
    ]
